version: "3.8"

services:
  frontend:
    image: deva1605/frontend:latest
    container_name: frontend
    ports:
      - "3000:5173"
    depends_on:
      - backend

  backend:
    image: deva1605/backend:latest
    container_name: backend
    ports:
      - "5000:5000"
